import { readFileSync, writeFileSync, existsSync, mkdirSync } from 'fs';
import { createHash } from 'crypto';
import { resolve, dirname } from 'path';
import { fileURLToPath } from 'url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const root = resolve(__dirname, '..');

const codePath = resolve(root, 'apps-script/Code.gs');
const manifestPath = resolve(root, 'apps-script/appsscript.json');
const outDir = resolve(root, 'src/lib');

const content = readFileSync(codePath, 'utf-8');
const manifestContent = readFileSync(manifestPath, 'utf-8');

const filtered = content.split('\n').filter(line => !/SCRIPT_INTEGRITY\s*=/.test(line));
const hash = createHash('sha256').update(filtered.join('\n')).digest('hex');

if (!existsSync(outDir)) mkdirSync(outDir, { recursive: true });

writeFileSync(
  resolve(outDir, 'backendChecksum.ts'),
  `// Auto-generated by build — do not edit\nexport const EXPECTED_BACKEND_HASH = '${hash}';\n`,
  'utf-8'
);

const escape = (s: string) => s.replace(/\\/g, '\\\\').replace(/`/g, '\\`').replace(/\$/g, '\\$');
writeFileSync(
  resolve(outDir, 'bundledBackend.ts'),
  `// Auto-generated by build — do not edit\nexport const BUNDLED_BACKEND_CODE = \`${escape(content)}\`;\nexport const BUNDLED_MANIFEST = \`${escape(manifestContent)}\`;\n`,
  'utf-8'
);
