// Mirrors apps-script/Code.gs:1011-1021 (function cleanGeminiText_).
// If you change one, update the other — there is no shared module.
import { describe, it, expect } from 'vitest';

function cleanGeminiText(text: string): string {
  return text
    .replace(/(?:Participants|Attendees|Présents)\s*:.*?(?=\n\n|\n[A-Z]|$)/is, '')
    .replace(/Notes\s+(?:par|by|generated by)\s+Gemini[^\n]*/gi, '')
    .replace(/^#{1,6}\s*/gm, '')
    .replace(/\*\*(.*?)\*\*/g, '$1')
    .replace(/\*(.*?)\*/g, '$1')
    .replace(/[ \t]{2,}/g, ' ')
    .replace(/\n{3,}/g, '\n\n')
    .trim();
}

describe('cleanGeminiText', () => {
  it('strips Participants block followed by blank line', () => {
    const input = 'Participants: Alice, Bob\n\nDiscussion started.';
    expect(cleanGeminiText(input)).toBe('Discussion started.');
  });

  it('strips Attendees block (English)', () => {
    const input = 'Attendees: Alice\n\nWe talked.';
    expect(cleanGeminiText(input)).toBe('We talked.');
  });

  it('strips Présents block (French)', () => {
    const input = 'Présents: Alice\n\nDiscussion.';
    expect(cleanGeminiText(input)).toBe('Discussion.');
  });

  it('removes "Notes by Gemini" footer line', () => {
    const input = 'Body text.\nNotes by Gemini in Meet';
    expect(cleanGeminiText(input)).toBe('Body text.');
  });

  it('removes "Notes par Gemini" footer (French)', () => {
    const input = 'Texte.\nNotes par Gemini dans Meet';
    expect(cleanGeminiText(input)).toBe('Texte.');
  });

  it('strips markdown headers # through ######', () => {
    const input = '# H1\n## H2\n###### H6\nBody';
    expect(cleanGeminiText(input)).toBe('H1\nH2\nH6\nBody');
  });

  it('strips bold **text** and italic *text* markers', () => {
    expect(cleanGeminiText('**bold** and *italic*')).toBe('bold and italic');
  });

  it('collapses runs of 2+ spaces/tabs to a single space', () => {
    expect(cleanGeminiText('a    b\t\tc')).toBe('a b c');
  });

  it('collapses 3+ consecutive newlines to exactly 2', () => {
    expect(cleanGeminiText('a\n\n\n\n\nb')).toBe('a\n\nb');
  });

  it('trims leading and trailing whitespace', () => {
    expect(cleanGeminiText('\n  hello  \n')).toBe('hello');
  });

  it('is idempotent on already-clean text', () => {
    const clean = 'Line one.\n\nLine two.';
    expect(cleanGeminiText(clean)).toBe(clean);
  });
});
